/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Projekt_indywidualny;

public class MainProgram {
	public static void main(String[] args){
    	System.out.print("elo");
        return;
    }
}
