/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Projekt_indywidualny;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        MainProgram classUnderTest = new MainProgram();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
